import { Platform, StyleSheet } from 'react-native';

export const createStyles = () =>
  StyleSheet.create({
    page: {
      flex: 1,
      backgroundColor: '#FFFFFF',
    },
    container2: {
      flex: 1,
      position: 'relative',
    },
    map: {
      ...StyleSheet.absoluteFill,
      bottom: 90,
    },
    drawTouchOverlay: {
      ...StyleSheet.absoluteFill,
      bottom: 90,
      zIndex: 40,
    },
    topControlsRow: {
      position: 'absolute',
      top: Platform.OS === 'ios' ? 60 : 30,
      left: 16,
      right: 16,
      zIndex: 100,
    },
    drawHeader: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      zIndex: 130,
      paddingTop: Platform.OS === 'ios' ? 56 : 24,
      paddingBottom: Platform.OS === 'ios' ? 16 : 4,
      paddingHorizontal: 16,
      backgroundColor: '#FFFFFF',
      flexDirection: 'row',
      alignItems: 'center',
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.04,
      shadowRadius: 8,
      elevation: 3,
    },
    drawBackButton: {
      width: 44,
      height: 44,
      alignItems: 'flex-start',
      justifyContent: 'center',
    },
    drawBackIcon: {
      width: 18,
      height: 18,
    },
    drawHeaderTitle: {
      flex: 1,
      color: '#111111',
      fontSize: 20,
      fontWeight: '600',
      textAlign: 'center',
    },
    drawHeaderSpacer: {
      width: 44,
      height: 44,
    },
    searchBarContainer: {
      backgroundColor: '#FFFFFF',
      borderRadius: 30,
      paddingHorizontal: 16,
      height: 54,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 4,
    },
    floatingUtilityButtons: {
      position: 'absolute',
      left: 16,
      zIndex: 120,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    drawActionSheet: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 110,
      backgroundColor: '#FFFFFF',
      borderTopLeftRadius: 26,
      borderTopRightRadius: 26,
      paddingTop: 20,
      paddingHorizontal: 22,
      paddingBottom: 38,
      flexDirection: 'row',
      gap: 14,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: -8 },
      shadowOpacity: 0.08,
      shadowRadius: 18,
      elevation: 12,
    },
    drawClearButton: {
      flex: 1,
      height: 52,
      borderRadius: 13,
      borderWidth: 1,
      borderColor: '#D1D5DB',
      backgroundColor: '#FFFFFF',
      alignItems: 'center',
      justifyContent: 'center',
    },
    drawClearButtonText: {
      color: '#9CA3AF',
      fontSize: 16,
      fontWeight: '700',
    },
    drawApplyButton: {
      flex: 1,
      height: 52,
      borderRadius: 13,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: '#24358E',
      shadowColor: '#1D2B6F',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.24,
      shadowRadius: 4,
      elevation: 4,
    },
    drawApplyButtonDisabled: {
      borderColor: '#AAB2D8',
      shadowOpacity: 0,
      elevation: 0,
    },
    drawApplyGradient: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    drawApplyButtonText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '800',
    },
    recenterButton: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: '#FFFFFF',
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 6,
      elevation: 3,
    },
    drawAreaButton: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: '#FFFFFF',
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 6,
      elevation: 3,
    },
    icon: {
      height: 20,
      width: 20,
    },
  });